-- ═══════════════════════════════════════════
-- 在 Supabase SQL Editor 中运行此文件
-- 路径：Supabase 后台 → SQL Editor → 粘贴 → Run
-- ═══════════════════════════════════════════

-- 1. 创建日记表
CREATE TABLE IF NOT EXISTS diary_entries (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id   UUID REFERENCES auth.users NOT NULL,
  date      DATE NOT NULL,
  title     TEXT DEFAULT '',
  content   TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, date)
);

-- 2. 更新时间触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON diary_entries
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 3. 开启 RLS（行级安全）
ALTER TABLE diary_entries ENABLE ROW LEVEL SECURITY;

-- 4. RLS 策略：只能看自己的日记
CREATE POLICY "Users can read own entries"
  ON diary_entries FOR SELECT
  USING (auth.uid() = user_id);

-- 5. RLS 策略：只能插入自己的日记
CREATE POLICY "Users can insert own entries"
  ON diary_entries FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- 6. RLS 策略：只能更新自己的日记
CREATE POLICY "Users can update own entries"
  ON diary_entries FOR UPDATE
  USING (auth.uid() = user_id);

-- 7. RLS 策略：只能删除自己的日记
CREATE POLICY "Users can delete own entries"
  ON diary_entries FOR DELETE
  USING (auth.uid() = user_id);

-- 8. 创建索引
CREATE INDEX IF NOT EXISTS idx_diary_entries_user_date
  ON diary_entries(user_id, date);
